/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package array;

/**
 *
 * @author tomama
 */
public class tugasarray extends javax.swing.JFrame {

    /**
     * Creates new form tugasarray
     */
    public tugasarray() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        jtxtnama = new javax.swing.JTextField();
        jtxtalamat = new javax.swing.JTextField();
        jtxtusia = new javax.swing.JTextField();
        jtxtjenis = new javax.swing.JTextField();
        jtxtgol = new javax.swing.JTextField();
        jtxtstatus = new javax.swing.JTextField();
        jtxtkewar = new javax.swing.JTextField();
        jtxtwaktu = new javax.swing.JTextField();
        jtxtspesial = new javax.swing.JTextField();
        al = new javax.swing.JLabel();
        us = new javax.swing.JLabel();
        jk = new javax.swing.JLabel();
        gd = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        kewar = new javax.swing.JLabel();
        wp = new javax.swing.JLabel();
        spesial = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Pemilihan Dokter");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 42));

        jLabel2.setText("Pilih Dokter");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 69, -1, -1));

        nama.setText("Nama");
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 127, 40, -1));

        jtxtnama.setEditable(false);
        jtxtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnamaActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 124, 160, -1));

        jtxtalamat.setEditable(false);
        getContentPane().add(jtxtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 155, 160, -1));

        jtxtusia.setEditable(false);
        getContentPane().add(jtxtusia, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 186, 160, -1));

        jtxtjenis.setEditable(false);
        getContentPane().add(jtxtjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 217, 160, -1));

        jtxtgol.setEditable(false);
        getContentPane().add(jtxtgol, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 248, 160, -1));

        jtxtstatus.setEditable(false);
        getContentPane().add(jtxtstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 279, 160, -1));

        jtxtkewar.setEditable(false);
        getContentPane().add(jtxtkewar, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 310, 160, -1));

        jtxtwaktu.setEditable(false);
        getContentPane().add(jtxtwaktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 341, 160, -1));

        jtxtspesial.setEditable(false);
        getContentPane().add(jtxtspesial, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 372, 160, -1));

        al.setText("Alamat");
        getContentPane().add(al, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 158, 40, -1));

        us.setText("Usia");
        getContentPane().add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 189, 40, -1));

        jk.setText("Jenis Kelamin");
        getContentPane().add(jk, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 220, 80, -1));

        gd.setText("Golongan Darah");
        getContentPane().add(gd, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 251, 100, -1));

        status.setText("Status");
        getContentPane().add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 282, 40, -1));

        kewar.setText("Kewarganegaraan");
        getContentPane().add(kewar, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 313, 110, -1));

        wp.setText("Waktu Praktek");
        getContentPane().add(wp, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 344, 100, -1));

        spesial.setText("Dokter Spesialis");
        getContentPane().add(spesial, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 375, 100, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu --", "DR. Farras Yassar", "DR. Anisa Putri", "DR. Harun Fajar" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 66, 150, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 307, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 350, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnamaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(jComboBox1.getSelectedItem().equals("DR. Farras Yassar"))
        {
            jtxtnama.setText("DR. Farras Yassar ");
            jtxtalamat.setText("Jl. Surabaya 16, Malang");
            jtxtusia.setText("20 Tahun");
            jtxtjenis.setText("Laki-Laki");
            jtxtgol.setText("A");
            jtxtstatus.setText("Belum Menikah");
            jtxtkewar.setText("Indonesia");
            jtxtwaktu.setText("Pagi (07.00-15.00)");
            jtxtspesial.setText("Dokter Umum");
        }
        else
        if(jComboBox1.getSelectedItem().equals("DR. Anisa Putri"))
        {
            jtxtnama.setText("DR. Anisa Putri ");
            jtxtalamat.setText("Jl. Veteran 3, Malang");
            jtxtusia.setText("20 Tahun");
            jtxtjenis.setText("Perempuan");
            jtxtgol.setText("O");
            jtxtstatus.setText("Belum Menikah");
            jtxtkewar.setText("Indonesia");
            jtxtwaktu.setText("Pagi (16.00-22.00)");
            jtxtspesial.setText("Dokter Gigi");
        }
        else
        if(jComboBox1.getSelectedItem().equals("DR. Harun Fajar"))
        {
            jtxtnama.setText("DR. Harun Fajar ");
            jtxtalamat.setText("Jl. Bandung 9, Malang");
            jtxtusia.setText("20 Tahun");
            jtxtjenis.setText("Laki - Laki");
            jtxtgol.setText("B");
            jtxtstatus.setText("Belum Menikah");
            jtxtkewar.setText("Indonesia");
            jtxtwaktu.setText("Pagi (22.00-06.00)");
            jtxtspesial.setText("Dokter Gizi");
        }
        
            
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugasarray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugasarray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugasarray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugasarray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugasarray().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel al;
    private javax.swing.JLabel gd;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jk;
    private javax.swing.JTextField jtxtalamat;
    private javax.swing.JTextField jtxtgol;
    private javax.swing.JTextField jtxtjenis;
    private javax.swing.JTextField jtxtkewar;
    private javax.swing.JTextField jtxtnama;
    private javax.swing.JTextField jtxtspesial;
    private javax.swing.JTextField jtxtstatus;
    private javax.swing.JTextField jtxtusia;
    private javax.swing.JTextField jtxtwaktu;
    private javax.swing.JLabel kewar;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel spesial;
    private javax.swing.JLabel status;
    private javax.swing.JLabel us;
    private javax.swing.JLabel wp;
    // End of variables declaration//GEN-END:variables
}
